version: '3'
services:
  app:
    build: 
      context: flask_app
      dockerfile: Dockerfile
    restart: always
    image: app:latest
    expose:
      - "5000"
    environment:
      APP_NAME: "application"

  nginx:
    build:
      context: nginx
      dockerfile: Dockerfile
    restart: always
    image: my-nginx:latest
    ports:
      - 80:80
    links:
      - app:app