version: '3'
services:
  app:
    restart: always
    image: app:latest
    expose:
      - "5000"
    environment:
      APP_NAME: "application"

  nginx:
    restart: always
    image: my-nginx:latest
    ports:
      - 80:80
    links:
      - app:app